### ISSUE TITLE
Segfault hit in ipset

### ISSUE THREAD

**Issue by lwr20** [projectcalico/felix#1181]
Seen during an FV run in `calicotest.openstack.test_status_reporting.TestEndpointStatusReporting.test_restart_port_up_down`: 
http://localhost:8080/view/Testing/job/run-gce-fv/PKG_SRC_STEM=master,SYSTEM_TYPE=ubuntu_kilo,TEST_SPEC=full-fv/538/consoleText
```
2016-11-22 01:46:51,565 [ERROR][26609] calicotest.openstack.basetest 195: ***** Start of errors in logs from /var/log/calico/felix.log on jenkins-fv-538-ubuntu-kilo-compute-node02 *****

=== LOG 2016-11-22 01:44:52 ERROR [pid 11379] ===
calico.felix.actor 395: _finish_msg_batch failed.
Traceback (most recent call last):
File "site-packages/calico/felix/actor.py", line 382, in _step
File "site-packages/calico/felix/ipsets.py", line 345, in _finish_msg_batch
File "site-packages/calico/felix/ipsets.py", line 384, in _sync_to_ipset
File "site-packages/calico/felix/ipsets.py", line 541, in replace_members
File "site-packages/calico/felix/ipsets.py", line 550, in _exec_and_commit
File "site-packages/calico/felix/futils.py", line 355, in check_call
FailedSystemCall: Failed system call (retcode : -15, args : ('ipset', 'restore'))
stdout  :
stderr  :
input  : create felix-calico-hosts-4-tmp hash:ip family inet maxelem 1048576 --exist
flush felix-calico-hosts-4-tmp
swap felix-calico-hosts-4 felix-calico-hosts-4-tmp
destroy felix-calico-hosts-4-tmp
COMMIT



=== LOG 2016-11-22 01:44:52 ERROR [pid 11379] ===
calico.felix.actor 395: _finish_msg_batch failed.
Traceback (most recent call last):
File "site-packages/calico/felix/actor.py", line 382, in _step
File "site-packages/calico/felix/ipsets.py", line 345, in _finish_msg_batch
File "site-packages/calico/felix/ipsets.py", line 384, in _sync_to_ipset
File "site-packages/calico/felix/ipsets.py", line 541, in replace_members
File "site-packages/calico/felix/ipsets.py", line 550, in _exec_and_commit
File "site-packages/calico/felix/futils.py", line 355, in check_call
FailedSystemCall: Failed system call (retcode : -15, args : ('ipset', 'restore'))
stdout  :
stderr  :
input  : create felix-calico-hosts-4-tmp hash:ip family inet maxelem 1048576 --exist
flush felix-calico-hosts-4-tmp
swap felix-calico-hosts-4 felix-calico-hosts-4-tmp
destroy felix-calico-hosts-4-tmp
COMMIT




2016-11-22 01:46:51,566 [ERROR][26609] calicotest.openstack.basetest 197: ****** End of errors in logs from /var/log/calico/felix.log on jenkins-fv-538-ubuntu-kilo-compute-node02 ******
```

@fasaxc says that signal 15 is segfault.  

Felix will crash and be restarted when this is hit, so no visible user impact.  We should probably catch and retry this action rather than crashing?

**Comment by fasaxc** [comment]
Might be able to put in a retry for this in the golang DP driver.

**Comment by fasaxc** [comment]
Retry added under #1202
