### ISSUE TITLE
felix can't read from etcd cluster: connection reset by peer

### ISSUE THREAD

**Issue by davison** [projectcalico/felix#1190]
I run the calico-node docker container (v0.23.0) and in my felix logs, I have the following repeating every couple of seconds;

```
2016-11-29 11:38:45,367 [ERROR][13132/140492136380160] calico.etcddriver.protocol 167: Failed to read from socket: error(104, 'Connection reset by peer')
2016-11-29 11:38:45,369 [INFO][13132/140492136380160] calico.etcddriver.driver 237: Reader thread shutting down, triggering stop event
2016-11-29 11:38:45,370 [INFO][13132/140492127987456] calico.etcddriver.hwm 105: Stopped tracking deletions
2016-11-29 11:38:45,370 [INFO][13132/140492136380160] calico.etcddriver.driver 209: Stopping driver
Exception in thread reader-thread:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "site-packages/calico/etcddriver/driver.py", line 218, in _read_from_socket
  File "site-packages/calico/etcddriver/protocol.py", line 159, in new_messages
error: [Errno 104] Connection reset by peer
2016-11-29 11:38:45,370 [INFO][13132/140492127987456] calico.etcddriver.driver 616: First resync: skipping deletion scan

2016-11-29 11:38:45,370 [INFO][13132/140492127987456] calico.etcddriver.driver 766: Sending status to Felix: in-sync
2016-11-29 11:38:45,370 [ERROR][13132/140492127987456] calico.etcddriver.protocol 129: Failed to write to socket
Traceback (most recent call last):
  File "site-packages/calico/etcddriver/protocol.py", line 127, in flush
  File "socket.py", line 228, in meth
error: [Errno 32] Broken pipe
2016-11-29 11:38:45,371 [ERROR][13132/140492127987456] calico.etcddriver.driver 325: Write to Felix failed; shutting down.
Traceback (most recent call last):
  File "site-packages/calico/etcddriver/driver.py", line 318, in _resync_and_merge
  File "site-packages/calico/etcddriver/driver.py", line 771, in _send_status
  File "site-packages/calico/etcddriver/protocol.py", line 110, in send_message
  File "site-packages/calico/etcddriver/protocol.py", line 130, in flush
WriteFailed: [Errno 32] Broken pipe
2016-11-29 11:38:45,371 [INFO][13132/140492127987456] calico.etcddriver.driver 209: Stopping driver
2016-11-29 11:38:45,371 [INFO][13132/140492127987456] calico.etcddriver.driver 356: Stop event set, exiting resync loop.
```

The environment passed to docker specifies `-e ETCD_ENDPOINTS=http://master.mesos:4001` and this is picked up correctly, as the felix logs also contain the following;
```
2016-11-29 11:41:53,748 [INFO][15793/2] calico.felix.config 502: Parameter EtcdEndpoints (Comma separated list of etcd endpoints, of the form scheme://address:port.  For example "https://1.2.3.4:2379,https://1.2.3.5:2379".  This option overrides EtcdScheme and EtcdAddr.) has value 'http://master.mesos:4001' read from Environment variable FELIX_ETCDENDPOINTS
```

If I exec into the calico-node container, I can reach the etcd cluster at that address and output the version string, so basic connectivity and communication with etcd look to be working:

```
dcos-slave3 ~ # docker exec -it calico-node /bin/sh
/ # nc -v master.mesos 4001
master.mesos (172.23.22.13:4001) open
GET /version HTTP/1.1
Host: master.mesos

HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 29 Nov 2016 10:44:50 GMT
Content-Length: 45

{"etcdserver":"3.0.15","etcdcluster":"3.0.0"}
```

Don't think this is a version mismatch, @matthewdupre mentioned in a chat session that etcd version shouldn't matter.

**Comment by davison** [comment]
just for completeness, I downgraded the etcd cluster to 2.3.7 and verified that the same error is output to the logs by felix.

**Comment by davison** [comment]
It appears that the `rp_filter` kernel param setting is the root cause of this.  We had this in our logs but thought it a red herring as it looked from the code as though it would cause a log message but not prevent felix from restarting.  Guess I read the code wrong!  I put a workaround into my comment on https://github.com/projectcalico/calico-containers/issues/1082

I'll close this for now as I think the one above will resolve it when released and people can use the `--ignore` setting for the kernel sys value.
