### ISSUE TITLE
(Rare) failure to delete temp hosts IP set; succeeded after felix restarted

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1230]
Seen in a scale run of 2.0.0-rc5 on a single server (of 1,000).  The ipset command to destroy the temporary IP set apparently failed.  Suspiciously, there appeared to be an ipset cleanup in progress at the time.  At a guess, the cleanup was listing the ipsets or otherwise accessing them, causing them to be locked so they couldn't be deleted.

Felix died as a result of the error and was restarted by the init script.  It then succeeded in updating the IP set.  Since it's rare and the automatic restart fixes it, I don't think we need to fix this, but it'd be good to design it out of the golang DP driver in 2.1.0 (for example by avoiding concurrent IP set updates and retrying a small number of times on failure).

```
2016-12-10 00:47:33,927 [INFO][117/3] calico.felix.ipsets 319: Replacing members of ipset IpsetActor<None,queue_len=0,live=True,msg=M43c4df12c9a907e6 (replace_members),time=3.638s> with 895 IPs
2016-12-10 00:47:33,928 [INFO][117/3] calico.felix.ipsets 505: Rewriting ipset <calico.felix.ipsets.Ipset object at 0x7f18d54b2ad0> with 895 members
2016-12-10 00:47:33,930 [INFO][117/14] calico.felix.fiptables 438: Graceful restart window finished, stubbing out chains: set([])
2016-12-10 00:47:33,934 [INFO][117/14] calico.felix.fiptables 470: Cleanup finished, deleted 0 chains, failed to delete these chains: set([])
2016-12-10 00:47:33,938 [INFO][117/14] calico.felix.fiptables 529: IptablesUpdater<v6-filter,queue_len=0,live=True,msg=None,time=0.031s> no updates in this batch.
2016-12-10 00:47:33,939 [INFO][117/22] calico.felix.splitter 232: iptables cleanup complete, moving on to ipsets
2016-12-10 00:47:33,940 [INFO][117/6] calico.felix.ipsets 165: Cleaning up left-over ipsets.
2016-12-10 00:47:33.945 [WARNING][99] stats_collector.go 127: Failed to report stats error=Stats channel blocked
2016-12-10 00:47:33.945 [WARNING][99] stats_collector.go 127: Failed to report stats error=Stats channel blocked
2016-12-10 00:47:33.946 [WARNING][99] stats_collector.go 127: Failed to report stats error=Stats channel blocked
2016-12-10 00:47:33.947 [WARNING][99] stats_collector.go 127: Failed to report stats error=Stats channel blocked
2016-12-10 00:47:33.948 [WARNING][99] stats_collector.go 127: Failed to report stats error=Stats channel blocked
2016-12-10 00:47:33,949 [ERROR][117/3] calico.felix.actor 395: _finish_msg_batch failed.
Traceback (most recent call last):
  File "site-packages/calico/felix/actor.py", line 382, in _step
  File "site-packages/calico/felix/ipsets.py", line 345, in _finish_msg_batch
  File "site-packages/calico/felix/ipsets.py", line 384, in _sync_to_ipset
  File "site-packages/calico/felix/ipsets.py", line 541, in replace_members
  File "site-packages/calico/felix/ipsets.py", line 550, in _exec_and_commit
  File "site-packages/calico/felix/futils.py", line 355, in check_call
FailedSystemCall: Failed system call (retcode : 1, args : ('ipset', 'restore'))
  stdout  : 
  stderr  : ipset v6.29: Error in line 899: Set cannot be destroyed: it is in use by a kernel component

  input  : create felix-calico-hosts-4-tmp hash:ip family inet maxelem 1048576 --exist
flush felix-calico-hosts-4-tmp
add felix-calico-hosts-4-tmp 10.240.0.191
add felix-calico-hosts-4-tmp 10.240.0.190
add felix-calico-hosts-4-tmp 10.240.0.193
add felix-calico-hosts-4-tmp 10.240.0.192
add felix-calico-hosts-4-tmp 10.240.0.195
add felix-calico-hosts-4-tmp 10.240.0.194
add felix-calico-hosts-4-tmp 10.240.0.197
add felix-calico-hosts-4-tmp 10.240.0.196
add felix-calico-hosts-4-tmp 10.240.0.199
add felix-calic...<snip>...calico-hosts-4-tmp 10.240.0.73
add felix-calico-hosts-4-tmp 10.240.97.214
add felix-calico-hosts-4-tmp 10.240.0.71
add felix-calico-hosts-4-tmp 10.240.97.221
add felix-calico-hosts-4-tmp 10.240.97.219
add felix-calico-hosts-4-tmp 10.240.97.218
add felix-calico-hosts-4-tmp 10.240.17.48
add felix-calico-hosts-4-tmp 10.240.0.44
add felix-calico-hosts-4-tmp 10.240.0.79
add felix-calico-hosts-4-tmp 10.240.0.78
swap felix-calico-hosts-4 felix-calico-hosts-4-tmp
destroy felix-calico-hosts-4-tmp
COMMIT


TrackedAsyncResult ('<disabled>', '<disabled>', 'IpsetActor', 'replace_members') was leaked with exception FailedSystemCall('ipset', 'restore').  Dying.
2016-12-10 00:47:33.952 [ERROR][99] felix.go 476: Failed to read from front-end socket error=EOF
2016-12-10 00:47:33.952 [WARNING][99] felix.go 304: Driver process stopped error=exit status 1
2016-12-10 00:47:33.952 [WARNING][99] felix.go 321: Felix is shutting down reason=Failed to read from front-end socket
2016-12-10 00:47:33.952 [INFO][99] felix.go 335: Driver still running, trying to shut it down...
2016-12-10 00:47:33.952 [INFO][99] felix.go 347: Driver shut down after SIGTERM
```

**Comment by lwr20** [comment]
Hit again.  Again, 1K node test using rc5.

**Comment by fasaxc** [comment]
Added a retry in #1202
