### ISSUE TITLE
ERROR log about IP route programming failure

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/felix#1240]
For example:

    === LOG 2016-12-18 13:49:17 ERROR [pid 6019] ===
    calico.felix.endpoint 1070: Cannot delete routes for interface tap72415b26-22 for WloadEndpointId<72415b26-22f1-460d-8792-f84a8cb0a73e>
    Traceback (most recent call last):
    File "site-packages/calico/felix/endpoint.py", line 1061, in _deconfigure_interface
    File "site-packages/calico/felix/devices.py", line 328, in set_routes
    File "site-packages/calico/felix/devices.py", line 199, in list_interface_route_ips
    File "site-packages/calico/felix/futils.py", line 355, in check_call
    FailedSystemCall: Failed system call (retcode : 1, args : ('ip', 'route', 'list', 'dev', u'tap72415b26-22'))
    stdout  :
    stderr  : Cannot find device "tap72415b26-22"
    
    input  : None

**Comment by neiljerram** [comment]
We detect an ERROR log like this in the tear down of 3 of our FV test classes - TestFlapInterfaces, TestIpv4, TestLargeSecurityGroups - when testing on Ubuntu with Kilo OpenStack.
