### ISSUE TITLE
Cannot delete routes error, interface gone?

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1263]
Probably benign log spam: seen in Jenkins run-gce-fv 787:

```
=== LOG 2017-01-12 16:25:59 ERROR [pid 28228] ===
calico.felix.endpoint 1162: Cannot delete routes for interface tape18557b2-0e for WloadEndpointId<e18557b2-0e0b-4964-b699-f2187c18ebb6>
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/calico/felix/endpoint.py", line 1153, in _deconfigure_interface
devices.set_routes(self.ip_type, set(), self._iface_name, None)
File "/usr/lib/python2.7/site-packages/calico/felix/devices.py", line 328, in set_routes
current_ips = list_interface_route_ips(ip_type, interface)
File "/usr/lib/python2.7/site-packages/calico/felix/devices.py", line 199, in list_interface_route_ips
["ip", "route", "list", "dev", interface]).stdout
File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 355, in check_call
args, retcode, stdout, stderr, input=input_str)
FailedSystemCall: Failed system call (retcode : 1, args : ('ip', 'route', 'list', 'dev', u'tape18557b2-0e'))
stdout  :
stderr  : Cannot find device "tape18557b2-0e"

input  : None
```

We swallow the error but it indicates that we've taken a path where the device didn't exist when we tried to remove its routes, then it did exist when we re-check it during the exception handler.

**Comment by fasaxc** [comment]
This code was removed in master and replaced with a netlink-based API call.
