### ISSUE TITLE
Usage reporting broken in 1.4 series

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1264]
I see this error in the logs, looks like the issue is that we renamed the `calico` package to `felix` so it can't find the metadata any more.
```
2017-01-13 10:42:54,077 [ERROR][2879/21] calico.felix.fetcd 367: Failed to look up calico's version
Traceback (most recent call last):
  File "site-packages/calico/felix/fetcd.py", line 365, in _periodically_usage_report
  File "site-packages/pkg_resources/__init__.py", line 963, in require
  File "site-packages/pkg_resources/__init__.py", line 849, in resolve
DistributionNotFound: The 'calico' distribution was not found and is required by the application
```

**Comment by fasaxc** [comment]
Fixed in 1.4.8.
