### ISSUE TITLE
calico-felix panics on rhel6 due to ip6tables-save -t nat

### ISSUE THREAD

**Issue by markfra** [projectcalico/felix#1319]
We are currently testing calico-felix-2.1.0-0.1.rc1.post7+20170202120128+0000+a43622e with these 2 patches on a RHEL6 client

https://github.com/projectcalico/felix/pull/1315
https://github.com/projectcalico/felix/pull/1318

It seems that calico-felix panics on "ip6tables-save -t nat" despite the fact that we have disabled ipv6 support in calico.cfg: Ipv6Support = false
Probably the config-options is being parsed but not passed down, since i cannot find any reference of this parameter in the source-code (other then config/config_params.go)
```
This is a snipped of the panic we observed:
2017-02-02 13:31:00.559 [INFO][32133] masq_mgr.go 144: IPAM pools updated, refreshing iptables rule ipVersion=0x6
2017-02-02 13:31:00.559 [INFO][32133] table.go 345: Queueing update of chain. chainName="cali-nat-outgoing" ipVersion=0x6 table="nat"
2017-02-02 13:31:00.560 [INFO][32133] ipset.go 239: Rewriting IP Set numMembers=6 setID="all-ipam-pools"
2017-02-02 13:31:00.575 [INFO][32133] ipset.go 255: Rewrote IP set numMembers=6 setID="all-ipam-pools"
2017-02-02 13:31:00.575 [INFO][32133] ipset.go 239: Rewriting IP Set numMembers=0 setID="masq-ipam-pools"
2017-02-02 13:31:00.579 [INFO][32133] ipset.go 255: Rewrote IP set numMembers=0 setID="masq-ipam-pools"
2017-02-02 13:31:00.579 [INFO][32133] ipset.go 239: Rewriting IP Set numMembers=1 setID="s:mOvkRfPKdYhPZuDVw9cMFw_wYCT-NtBaIy8YKw"
2017-02-02 13:31:00.580 [INFO][32133] ipset.go 255: Rewrote IP set numMembers=1 setID="s:mOvkRfPKdYhPZuDVw9cMFw_wYCT-NtBaIy8YKw"
2017-02-02 13:31:00.581 [INFO][32133] ipset.go 239: Rewriting IP Set numMembers=1 setID="all-ipam-pools"
2017-02-02 13:31:00.582 [INFO][32133] ipset.go 255: Rewrote IP set numMembers=1 setID="all-ipam-pools"
2017-02-02 13:31:00.582 [INFO][32133] ipset.go 239: Rewriting IP Set numMembers=0 setID="masq-ipam-pools"
2017-02-02 13:31:00.583 [INFO][32133] ipset.go 255: Rewrote IP set numMembers=0 setID="masq-ipam-pools"
2017-02-02 13:31:00.584 [INFO][32133] ipset.go 239: Rewriting IP Set numMembers=0 setID="s:mOvkRfPKdYhPZuDVw9cMFw_wYCT-NtBaIy8YKw"
2017-02-02 13:31:00.585 [INFO][32133] ipset.go 255: Rewrote IP set numMembers=0 setID="s:mOvkRfPKdYhPZuDVw9cMFw_wYCT-NtBaIy8YKw"
2017-02-02 13:31:00.585 [INFO][32133] table.go 373: Scanning for out-of-sync iptables chains ipVersion=0x4 table="nat"
2017-02-02 13:31:00.591 [INFO][32133] table.go 414: Scanning for unexpected iptables chains ipVersion=0x4 table="nat"
2017-02-02 13:31:00.591 [INFO][32133] table.go 446: Done scanning, in sync with dataplane ipVersion=0x4 table="nat"
2017-02-02 13:31:00.591 [INFO][32133] table.go 373: Scanning for out-of-sync iptables chains ipVersion=0x6 table="nat"
2017-02-02 13:31:00.631 [WARNING][32133] table.go 488: ip6tables-save command failed error=exit status 1 ipVersion=0x6 table="nat"
2017-02-02 13:31:00.736 [WARNING][32133] table.go 488: ip6tables-save command failed error=exit status 1 ipVersion=0x6 table="nat"
2017-02-02 13:31:00.941 [WARNING][32133] table.go 488: ip6tables-save command failed error=exit status 1 ipVersion=0x6 table="nat"
2017-02-02 13:31:01.346 [WARNING][32133] table.go 488: ip6tables-save command failed error=exit status 1 ipVersion=0x6 table="nat"
2017-02-02 13:31:01.346 [PANIC][32133] table.go 494: ip6tables-save command failed after retries ipVersion=0x6 table="nat"
panic: (*logrus.Entry) (0x1710760,0xc42079ea50)

goroutine 56 [running]:
panic(0x1710760, 0xc42079ea50)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.Entry.log(0xc4200405f0, 0xc4203b3470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420679300, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc4204e08c0, 0xc420679370, 0x1, 0x1)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*Entry).Panicf(0xc4204e08c0, 0x176b07b, 0x1f, 0xc420679420, 0x1, 0x1)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:217 +0x101
github.com/projectcalico/felix/iptables.(*Table).getHashesFromDataplane(0xc42049f400, 0xc420679660)
	/go/src/github.com/projectcalico/felix/iptables/table.go:494 +0x346
github.com/projectcalico/felix/iptables.(*Table).loadDataplaneState(0xc42049f400)
	/go/src/github.com/projectcalico/felix/iptables/table.go:374 +0x113
github.com/projectcalico/felix/iptables.(*Table).Apply(0xc42049f400)
	/go/src/github.com/projectcalico/felix/iptables/table.go:586 +0x856
github.com/projectcalico/felix/intdataplane.(*InternalDataplane).apply(0xc420472d80)
	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:493 +0x174
github.com/projectcalico/felix/intdataplane.(*InternalDataplane).loopUpdatingDataplane(0xc420472d80)
	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:445 +0xf2a
created by github.com/projectcalico/felix/intdataplane.(*InternalDataplane).Start
	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:288 +0x43
```

**Comment by wmuizelaar** [comment]
https://github.com/projectcalico/felix/pull/1320 fixes this issue.
