### ISSUE TITLE
Intermittent failure of booting VM to get DHCP response, when attached to a complex security group

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/felix#1333]
We are seeing intermittent failures in the setup phase of our TestLargeSecurityGroup test, like:

    Traceback (most recent call last):
      File "/home/core/calico-test/env/lib/python2.7/site-packages/nose/suite.py", line 209, in run
        self.setUp()
      File "/home/core/calico-test/env/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
        self.setupContext(ancestor)
      File "/home/core/calico-test/env/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
        try_run(context, names)
      File "/home/core/calico-test/env/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
        return func()
      File "/home/core/calico-test/calicotest/common/testutils.py", line 83, in wrapped_set_up_class
        set_up_class(cls)
      File "/home/core/calico-test/calicotest/openstack/test_security_groups.py", line 341, in setUpClass
        cls.vms.append(vm_thread.join())
      File "/home/core/calico-test/calicotest/common/testutils.py", line 327, in join
        raise self._exception
    RuntimeError: Failed to SSH into 10.28.0.70:
    timed out

The pattern of occurrences so far indicates:
- happening with OpenStack Liberty and Mitaka on CentOS 7, but not with OpenStack Kilo on Ubuntu Trusty
- happening with current master Felix/networking-calico code (Feb 9th 2017) but not with code from the packages in our 'calico-1.4' PPA.

Investigation of one occurrence found that the VM had not got a response to its DHCP requests, so did not know its own IP address.  Dnsmasq logs (in syslog) showed no trace of having _received_ those requests (whereas they usually do), and the dnsmasq `host` file _did_ have the expected MAC/IP address mapping for that VM.  So it looks like there was some break in the datapath between the VM and Dnsmasq, at the time that the VM issued its DHCP requests.

**Comment by neiljerram** [comment]
A full transcript of my investigation of the occurrence summarised above is at http://pastebin.com/WvvvvRjb.  The IP that couldn't be accessed, in that occurrence, was 10.28.0.73.

**Comment by fasaxc** [comment]
Looks like Felix is "cleaning up" a rule inserted by the DHCP agent:
```
2017-02-13 01:47:54.267 [INFO][29707] table.go 416: Loading current iptables state and checking it is correct. ipVersion=0x4 table="filter"
2017-02-13 01:47:54.271 [INFO][29707] table.go 598: Found inserted rule from previous Felix version, marking for cleanup. chainName="INPUT" ipVersion=0x4 line="-A INPUT -j calico-dhcp-agen-INPUT\n" rule="-A INPUT -j calico-dhcp-agen-INPUT\n" table="filter"
2017-02-13 01:47:54.271 [INFO][29707] table.go 598: Found inserted rule from previous Felix version, marking for cleanup. chainName="FORWARD" ipVersion=0x4 line="-A FORWARD -j calico-dhcp-agen-FORWARD\n" rule="-A FORWARD -j calico-dhcp-agen-FORWARD\n" table="filter"
2017-02-13 01:47:54.271 [INFO][29707] table.go 598: Found inserted rule from previous Felix version, marking for cleanup. chainName="OUTPUT" ipVersion=0x4 line="-A OUTPUT -j calico-dhcp-agen-OUTPUT\n" rule="-A OUTPUT -j calico-dhcp-agen-OUTPUT\n" table="filter"
2017-02-13 01:47:54.272 [INFO][29707] table.go 598: Found inserted rule from previous Felix version, marking for cleanup. chainName="neutron-filter-top" ipVersion=0x4 line="-A neutron-filter-top -j calico-dhcp-agen-local\n" rule="-A neutron-filter-top -j calico-dhcp-agen-local\n" table="filter"
2017-02-13 01:47:54.272 [WARNING][29707] table.go 444: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "OLD INSERT RULE", "wUHhoiAYhphO9Mso", "", ""} chainName="FORWARD" expectedRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", ""} ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [WARNING][29707] table.go 444: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"OLD INSERT RULE"} chainName="neutron-filter-top" expectedRuleIDs=[]string{} ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [WARNING][29707] table.go 444: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "OLD INSERT RULE", "tVnHkvAo15HuiPy0", "", ""} chainName="OUTPUT" expectedRuleIDs=[]string{"tVnHkvAo15HuiPy0", "", "", ""} ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [WARNING][29707] table.go 444: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"OLD INSERT RULE", "Cz_u1IQiXIMmKD4c", ""} chainName="INPUT" expectedRuleIDs=[]string{"Cz_u1IQiXIMmKD4c", ""} ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [INFO][29707] table.go 486: Found unexpected chain, marking for cleanup chainName="calico-dhcp-agen-FORWARD" ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [INFO][29707] table.go 486: Found unexpected chain, marking for cleanup chainName="calico-dhcp-agen-local" ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [INFO][29707] table.go 486: Found unexpected chain, marking for cleanup chainName="calico-dhcp-agen-INPUT" ipVersion=0x4 table="filter"
2017-02-13 01:47:54.272 [INFO][29707] table.go 486: Found unexpected chain, marking for cleanup chainName="calico-dhcp-agen-OUTPUT" ipVersion=0x4 table="filter"
```

**Comment by fasaxc** [comment]
Hmm, definitely a problem that we're fighting over those rules but those particular rules seem to be a red herring; the DHCP agent doesn't put anything in the filter table.  Might be something else less obvious that we're clobbering, though.

**Comment by fasaxc** [comment]
Re-opening until we're sure the speculative fix does the trick.

**Comment by fasaxc** [comment]
Another possible smoking gun; the DHCP agent is trying to write to iptables and failing at around the time that the failing VM was created.  Could the exception be bypassing some other processing?
```
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent [req-5dee278f-f466-4329-aeae-26b0c98fd3e4 - - - - -] Unable to restart dhcp for 58aa0b58-0b9c-4231-84fe-913568f52c36.
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 115, in call_driver
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 138, in restart
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     self.enable()
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 206, in enable
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     interface_name = self.device_manager.setup(self.network)
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 1233, in setup
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     self.fill_dhcp_udp_checksums(namespace=network.namespace)
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 1299, in fill_dhcp_udp_checksums
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     iptables_mgr.apply()
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py", line 423, in apply
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     return self._apply()
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py", line 431, in _apply
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     return self._apply_synchronized()
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py", line 508, in _apply_synchronized
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     '\n'.join(log_lines))
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 195, in __exit__
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     six.reraise(self.type_, self.value, self.tb)
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py", line 487, in _apply_synchronized
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     run_as_root=True)
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 159, in execute
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent     raise RuntimeError(m)
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent RuntimeError:
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent Command: ['sudo', 'iptables-restore', '-n']
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent Exit code: 1
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent Stdin: # Generated by iptables_manager
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent *filter
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D FORWARD 1
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I FORWARD 3 -m comment --comment "cali:wUHhoiAYhphO9Mso" -j cali-FORWARD
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I INPUT 1 -j calico-dhcp-agen-INPUT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D INPUT 3
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D OUTPUT 1
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I OUTPUT 3 -m comment --comment "cali:tVnHkvAo15HuiPy0" -j cali-OUTPUT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent COMMIT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent # Completed by iptables_manager
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent # Generated by iptables_manager
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent *nat
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I OUTPUT 1 -j calico-dhcp-agen-OUTPUT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D OUTPUT 3
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D POSTROUTING 1
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I POSTROUTING 3 -m comment --comment "cali:O3lYWMrLQYEMJtB5" -j cali-POSTROUTING
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I PREROUTING 1 -j calico-dhcp-agen-PREROUTING
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D PREROUTING 3
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent COMMIT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent # Completed by iptables_manager
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent # Generated by iptables_manager
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent *raw
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I OUTPUT 1 -j calico-dhcp-agen-OUTPUT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D OUTPUT 3
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -I PREROUTING 1 -j calico-dhcp-agen-PREROUTING
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent -D PREROUTING 3
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent COMMIT
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent # Completed by iptables_manager
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent Stdout:
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent Stderr: iptables-restore: line 9 failed
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent
Feb 14 10:59:33 jenkins-fv-smc-centos-liberty-compute-node02 calico-dhcp-agent[16026]: 2017-02-14 10:59:33.742 16026 ERROR neutron.agent.dhcp.agent

```

**Comment by fasaxc** [comment]
I hacked in a workaround in dhcp.py:
```
            while True:
                try:
                    self.fill_dhcp_udp_checksums(namespace=network.namespace)
                except RuntimeError:
                    LOG.exception("Failed to insert UDP checksum rule")
                    time.sleep(0.1)
                else:
                    break
```
After 5-10 runs, I've hit the retry a few times but had no test failures.

**Comment by fasaxc** [comment]
Productising the fix under this gerrit job: https://review.openstack.org/#/c/433702/1
