### ISSUE TITLE
Felix errors on Virtuozzo Linux

### ISSUE THREAD

**Issue by jaxxstorm** [projectcalico/felix#1335]
I am running felix which is bundled under canal (ie Calico + Flannel for overlay) on Virtuozzo Linux. Here's my versions/outputs:

OS/Kernel
```
# cat /etc/redhat-release
Virtuozzo Linux release 7.3
# uname -a
Linux tukd-srv-0086.dapt.to 3.10.0-327.36.1.vz7.20.18 #1 SMP Tue Dec 20 13:52:43 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Flannel/Calico:

```
# docker ps --format {{.Image}} | grep -i quay
quay.io/calico/node:v1.0.1
quay.io/coreos/flannel:v0.7.0
quay.io/calico/cni:v1.5.5
```

I was having trouble with pod communication on some nodes, and as I started digging I found that working pods have the felix routes set up for pods like so:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    0      0        0 bond0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.29.140.0    0.0.0.0         255.255.254.0   U     0      0        0 bond0
172.29.140.0    0.0.0.0         255.255.254.0   U     0      0        0 br0
192.168.0.0     0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
192.168.79.2    0.0.0.0         255.255.255.255 UH    0      0        0 cali3a6de3e18e6
192.168.79.4    0.0.0.0         255.255.255.255 UH    0      0        0 cali84e8e015c09
192.168.79.5    0.0.0.0         255.255.255.255 UH    0      0        0 cali21e2cc5baea
192.168.79.6    0.0.0.0         255.255.255.255 UH    0      0        0 cali376169917b4
192.168.79.7    0.0.0.0         255.255.255.255 UH    0      0        0 calief1f174766b
192.168.79.8    0.0.0.0         255.255.255.255 UH    0      0        0 cali84306e68353
```

and broken hosts (ie hosts with pods that can ping other pods, don't have the calico routes set up

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    0      0        0 bond0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.29.140.0    0.0.0.0         255.255.254.0   U     0      0        0 bond0
172.29.140.0    0.0.0.0         255.255.254.0   U     0      0        0 br0
192.168.0.0     0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
```
This led me to read the logs on the calico node and I found the following error:

```
2017-02-11 03:43:39,190 [ERROR][1867/14] calico.felix.actor 368: Exception processing M101b607cf213881a (_load_chain_names_from_iptables)
Traceback (most recent call last):
  File "site-packages/calico/felix/actor.py", line 366, in _step
  File "site-packages/calico/felix/fiptables.py", line 214, in _load_chain_names_from_iptables
  File "site-packages/gevent/subprocess.py", line 327, in check_output
CalledProcessError: Command '['ip6tables-save', '--table', 'filter']' returned non-zero exit status 1
2017-02-11 03:43:39,191 [INFO][1867/14] calico.felix.fiptables 563: IptablesUpdater<v6-filter,queue_len=0,live=True,msg=None,time=0.002s> no updates in this batch.
TrackedAsyncResult ('<disabled>', '<disabled>', 'IptablesUpdater(v6-filter)', '_load_chain_names_from_iptables') was leaked with exception CalledProcessError().  Dying.
2017-02-11 03:43:39.194 [ERROR][1843] felix.go 502: Failed to read from front-end socket error=EOF
2017-02-11 03:43:39.194 [WARNING][1843] felix.go 330: Driver process stopped error=exit status 1
2017-02-11 03:43:39.194 [WARNING][1843] felix.go 347: Felix is shutting down reason=Failed to read from front-end socket
2017-02-11 03:43:39.194 [INFO][1843] felix.go 361: Driver still running, trying to shut it down...
2017-02-11 03:43:39.194 [INFO][1843] felix.go 373: Driver shut down after SIGTERM
2017-02-11 03:43:39.194 [INFO][1843] felix.go 387: Shutdown wasn't cause by signal, pausing to avoid tight restart loop
```

I thought this might be due to missing kernel modules loaded into the volume mount `/lib/modules` across hosts, so I loaded a few missing modules onto the broken host:

```
modprobe ip_set
modprobe ip_set_hash_ip
modprobe ip6t_rpfilter
```

Unfortunately, that didn't seem to get the job done. What am I missing here? Is there something misconfigured on my canal nodes at this point?

**Comment by fasaxc** [comment]
Are you using IPv6? If not, disabling it in Calico's config may work around the issue. Look for the IPv6Support flash in our docs.

**Comment by jaxxstorm** [comment]
The issue was that Virtuozzo Linux uses a custom iptables chain, with its own iptables library to manage its cluser storage tool, Shamen. When I mapped /usr/lib64/xtables to /lib/xtables via volume mount into the container, iptables now works.

Sorry for the confusion
