### ISSUE TITLE
Crashes seen when running the k8s e2e tests with KDD

### ISSUE THREAD

**Issue by lwr20** [projectcalico/felix#1375]
Felix log shows:
```
2017-03-08 11:55:28.244 [PANIC][1274] table.go 695: Failed to program iptables, giving up after retries error=exit status 2 ipVersion=0x4 table="filter"
panic: (*logrus.Entry) (0x1725e00,0xc420441680)

goroutine 47 [running]:
panic(0x1725e00, 0xc420441680)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.Entry.log(0xc420012640, 0xc420117a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4205c1800, ...)
        /go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc420441630, 0xc4205c1978, 0x1, 0x1)
        /go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/projectcalico/felix/iptables.(*Table).Apply(0xc4200f8f00, 0x344db59)
        /go/src/github.com/projectcalico/felix/iptables/table.go:695 +0x8a1
github.com/projectcalico/felix/intdataplane.(*InternalDataplane).apply(0xc4203c7400)
        /go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:676 +0x21f
github.com/projectcalico/felix/intdataplane.(*InternalDataplane).loopUpdatingDataplane(0xc4203c7400)
        /go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:540 +0x73a
created by github.com/projectcalico/felix/intdataplane.(*InternalDataplane).Start
        /go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:334 +0x51
2017-03-08 11:55:28.328 [INFO][1314] logutils.go 80: Early screen log level set to debug
2017-03-08 11:55:28.331 [INFO][1314] felix.go 104: Felix starting up buildDate="2017-03-01T17:29:58+0000" gitCommit="1975720524fc9447cec6f76492342e19aa2e14b9" version="2.1.0-rc6"
```

**Comment by lwr20** [comment]
logs available currently on `jenkins-kdd-kubetest-master:/home/jenkins` - I'll get them uploaded to gist or something shortly...

**Comment by fasaxc** [comment]
Issue is that we're trying to render a port match without a specified protocol.  In python felix, that failed validation, resulting in a "Missing chain drop".

**Comment by caseydavenport** [comment]
Fixed by https://github.com/projectcalico/libcalico-go/pull/364
