### ISSUE TITLE
panic in felix/calc.(*EventSequencer).flushHostIPUpdates

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/felix#1435]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13aff86]

goroutine 83 [running]:
github.com/projectcalico/felix/calc.(*EventSequencer).flushHostIPUpdates(0xc420083600)
	/go/src/github.com/projectcalico/felix/calc/event_sequencer.go:422 +0xa6
github.com/projectcalico/felix/calc.(*EventSequencer).Flush(0xc420083600)
	/go/src/github.com/projectcalico/felix/calc/event_sequencer.go:530 +0xd7
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).maybeFlush(0xc420450400)
	/go/src/github.com/projectcalico/felix/calc/async_calc_graph.go:169 +0xe5
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).loop(0xc420450400)
	/go/src/github.com/projectcalico/felix/calc/async_calc_graph.go:157 +0x264
created by github.com/projectcalico/felix/calc.(*AsyncCalcGraph).Start
	/go/src/github.com/projectcalico/felix/calc/async_calc_graph.go:192 +0xe1
```

**Comment by neiljerram** [comment]
This is with current Felix master (57b9727), run with:
```
docker run --detach --privileged --name k8sfv-felix \
  -e FELIX_LOGSEVERITYSCREEN=info \
  -e FELIX_DATASTORETYPE=kubernetes \
  -e FELIX_PROMETHEUSMETRICSENABLED=true \
  -e FELIX_USAGEREPORTINGENABLED=false \
  -e 'FELIX_DEBUGMEMORYPROFILEPATH=heap-<timestamp>' \
  -e K8S_API_ENDPOINT=https://172.17.0.6:6443 \
  -e K8S_INSECURE_SKIP_TLS_VERIFY=true \
  -e K8SFV_LOG_LEVEL=debug \
  -v /home/neil/go/src/github.com/projectcalico/felix:/testcode \
  -w /testcode/k8sfv/output \
  calico/felix /bin/sh -c 'for n in 1 2; do calico-felix; done'
```
Felix is being driven, via KDD, by the k8sfv `should run label rotation test` test.

Info-level logs leading up to the panic:
```
2017-04-20 12:42:44.128 [INFO][37] async_calc_graph.go 138: First time we've been in sync
2017-04-20 12:42:44.129 [INFO][37] event_sequencer.go 192: Possible config update. global=map[string]string{"ClusterGUID":"51c24aa6f3c2412ba7d90ffa7745a8d0", "ClusterType":"KDD"} host=map[string]string{}
2017-04-20 12:42:44.129 [INFO][37] config_params.go 174: Merging in config from datastore (global): map[ClusterGUID:51c24aa6f3c2412ba7d90ffa7745a8d0 ClusterType:KDD]
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for PrometheusMetricsEnabled: true (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for PrometheusMetricsEnabled: true (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for LogSeverityScreen: info (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for LogSeverityScreen: INFO (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for DebugMemoryProfilePath: heap-<timestamp> (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for DebugMemoryProfilePath: heap-<timestamp> (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for DatastoreType: kubernetes (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for DatastoreType: kubernetes (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for UsageReportingEnabled: false (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for UsageReportingEnabled: false (from environment variable)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for MetadataAddr: None (from config file)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 292: Value set to 'none', replacing with zero-value: "".
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for MetadataAddr:  (from config file)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for LogFilePath: None (from config file)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 292: Value set to 'none', replacing with zero-value: "".
2017-04-20 12:42:44.129 [INFO][37] config_params.go 311: Parsed value for LogFilePath:  (from config file)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 275: Parsing value for LogSeverityFile: None (from config file)
2017-04-20 12:42:44.129 [INFO][37] config_params.go 292: Value set to 'none', replacing with zero-value: "".
2017-04-20 12:42:44.130 [INFO][37] config_params.go 311: Parsed value for LogSeverityFile:  (from config file)
2017-04-20 12:42:44.130 [INFO][37] config_params.go 275: Parsing value for ClusterGUID: 51c24aa6f3c2412ba7d90ffa7745a8d0 (from datastore (global))
2017-04-20 12:42:44.131 [INFO][37] int_dataplane.go 478: Received *proto.ActivePolicyUpdate update from calculation graph msg=id:<tier:"default" name:"ns.projectcalico.org/ns1-2-production" > policy:<inbound_rules:<action:"allow" rule_id:"uBMbPc553rNrdeYN" > outbound_rules:<action:"allow" rule_id:"BugpQzHvGkspxvT6" > > 
2017-04-20 12:42:44.132 [INFO][37] table.go 376: Queueing update of chain. chainName="cali-pi-_EYP1mrGQRq5Y_0ly9Qf" ipVersion=0x4 table="raw"
2017-04-20 12:42:44.132 [INFO][37] table.go 376: Queueing update of chain. chainName="cali-po-_EYP1mrGQRq5Y_0ly9Qf" ipVersion=0x4 table="raw"
2017-04-20 12:42:44.132 [INFO][37] table.go 376: Queueing update of chain. chainName="cali-pi-_EYP1mrGQRq5Y_0ly9Qf" ipVersion=0x4 table="filter"
2017-04-20 12:42:44.133 [INFO][37] table.go 376: Queueing update of chain. chainName="cali-po-_EYP1mrGQRq5Y_0ly9Qf" ipVersion=0x4 table="filter"
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by fasaxc** [comment]
Marking as v2.2.0 until we know the impact...

**Comment by neiljerram** [comment]
Another occurrence, from the `should delete a pod whose IP has been cleared` test:

```
2017-04-20 12:54:54.939 [INFO][104] int_dataplane.go 599: Finished applying updates to dataplane. msecToApply=5.178714
2017-04-20 12:54:59.076 [INFO][104] int_dataplane.go 584: Applying dataplane updates
2017-04-20 12:54:59.076 [INFO][104] route_table.go 141: Queueing a resync of routing table. ipVersion=0x4
2017-04-20 12:54:59.076 [INFO][104] route_table.go 141: Queueing a resync of routing table. ipVersion=0x6
2017-04-20 12:54:59.076 [INFO][104] ipsets.go 214: Asked to resync with the dataplane on next update. family="inet"
2017-04-20 12:54:59.076 [INFO][104] ipsets.go 214: Asked to resync with the dataplane on next update. family="inet6"
2017-04-20 12:54:59.076 [INFO][104] ipsets.go 242: Resyncing ipsets with dataplane. family="inet"
2017-04-20 12:54:59.076 [INFO][104] ipsets.go 242: Resyncing ipsets with dataplane. family="inet6"
2017-04-20 12:54:59.077 [INFO][104] ipsets.go 283: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=635.206µs
2017-04-20 12:54:59.077 [INFO][104] ipsets.go 283: Finished resync family="inet6" numInconsistenciesFound=0 resyncDuration=1.016632ms
2017-04-20 12:54:59.077 [INFO][104] int_dataplane.go 599: Finished applying updates to dataplane. msecToApply=1.364171
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13aff86]

goroutine 101 [running]:
github.com/projectcalico/felix/calc.(*EventSequencer).flushHostIPUpdates(0xc4202d46e0)
	/go/src/github.com/projectcalico/felix/calc/event_sequencer.go:422 +0xa6
github.com/projectcalico/felix/calc.(*EventSequencer).Flush(0xc4202d46e0)
	/go/src/github.com/projectcalico/felix/calc/event_sequencer.go:530 +0xd7
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).maybeFlush(0xc4204b5440)
	/go/src/github.com/projectcalico/felix/calc/async_calc_graph.go:169 +0xe5
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).loop(0xc4204b5440)
	/go/src/github.com/projectcalico/felix/calc/async_calc_graph.go:157 +0x264
created by github.com/projectcalico/felix/calc.(*AsyncCalcGraph).Start
	/go/src/github.com/projectcalico/felix/calc/async_calc_graph.go:192 +0xe1
```

**Comment by fasaxc** [comment]
Looks like this is the offending line:
```
hostIP.IP.String()
```
so we're getting a nil host IP.

In the real world, this shouldn't be nil, so I'm going to downgrade the issue.  OTOH, we should be validating against that in the validation filter.

**Comment by neiljerram** [comment]
@fasaxc I think this issue is fixed by https://github.com/projectcalico/libcalico-go/pull/449, isn't it?

**Comment by fasaxc** [comment]
Yes, should be!
