### ISSUE TITLE
Test flake: timeout waiting for container to die

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1610]
https://semaphoreci.com/calico/felix-2/branches/master/builds/694

Felix panicked as expected in this test:

```
2017-11-08 18:29:34.586 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] panic: (*logrus.Entry) (0x15294e0,0xc420434c80)
2017-11-08 18:29:34.586 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] 
2017-11-08 18:29:34.587 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] goroutine 147 [running]:
2017-11-08 18:29:34.588 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus.Entry.log(0xc42014c000, 0xc4202ab980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-11-08 18:29:34.588 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] 	/go/src/github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus/entry.go:125 +0x5e8
2017-11-08 18:29:34.588 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420434c30, 0xc420705f00, 0x1, 0x1)
2017-11-08 18:29:34.589 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] 	/go/src/github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus/entry.go:170 +0xaa
2017-11-08 18:29:34.589 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] github.com/projectcalico/felix/iptables.(*Table).Apply(0xc420150c60, 0x6aed79)
2017-11-08 18:29:34.589 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] 	/go/src/github.com/projectcalico/felix/iptables/table.go:786 +0x69f
2017-11-08 18:29:34.590 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] github.com/projectcalico/felix/intdataplane.(*InternalDataplane).apply.func3(0xc4202a6a90, 0xc4202a6a98, 0xc4202a6aa0, 0xc420150c60)
2017-11-08 18:29:34.590 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] 	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:866 +0x2f
2017-11-08 18:29:34.590 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] created by github.com/projectcalico/felix/intdataplane.(*InternalDataplane).apply
2017-11-08 18:29:34.590 [INFO][18502] containers.go 103: felix-18502-21-felixfv[stderr] 	/go/src/github.com/projectcalico/felix/intdataplane/int_dataplane.go:865 +0x41a
```

But the test failed because the container didn't die:

```
• Failure [39.285 seconds]
health tests
/go/src/github.com/projectcalico/felix/fv/health_test.go:214
  with Felix and Typha running
  /go/src/github.com/projectcalico/felix/fv/health_test.go:414
    after removing iptables-restore
    /go/src/github.com/projectcalico/felix/fv/health_test.go:272
      should become unready, then die [It]
      /go/src/github.com/projectcalico/felix/fv/health_test.go:285

      Timed out after 5.001s.
      Expected
          <bool>: false
      to be true

      /go/src/github.com/projectcalico/felix/fv/health_test.go:287
```

## Expected Behavior

container dying within timeout
## Current Behavior

flake
## Possible Solution

extend timeout
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by fasaxc** [comment]
I think this was caused by overloading Semaphore's box.  It was resolved by splitting the semaphore job into batches and avoiding running too many threads in each batch.
