### ISSUE TITLE
Test flake: workload set-up failure: cannot alloc memory

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1663]
```
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: panic: failed to create namespace: cannot allocate memory
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: 
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: goroutine 1 [running]:
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: main.panicIfError(0x1ab34e0, 0xc4202d2010)
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: /go/src/github.com/projectcalico/felix/fv/test-workload/test-workload.go:191 +0x4a
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: main.main()
2017-12-20 10:42:55.877 [INFO][85386] workload.go 121: Workload w2 stderr: /go/src/github.com/projectcalico/felix/fv/test-workload/test-workload.go:59 +0x317
```

Might be worth adding a retry there in the hopes that the problem is transient

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`): 14b3d8237d45ded413fa774e79f0f5bc6e6e98b7

**Comment by fasaxc** [comment]
Speculative fix in, closing this for now.
