### ISSUE TITLE
Named port in NetworkPolicy crashes felix

### ISSUE THREAD

**Issue by redbaron** [projectcalico/felix#1685]
## Current Behavior

Following network policy is accepted by APIServer, but causes calico running kubernetes datastore to crash:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apps-report-pipeline-me
spec:
  egress:
  - ports:
    - port: postgresql
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: apps-report-pipeline-me-postgresql
  podSelector:
    matchLabels:
      app: apps-report-pipeline-me
  policyTypes:
  - Egress
```

Panic log:
```
2018-01-23 11:39:02.230 [INFO][717] int_dataplane.go 574: Received *proto.ConfigUpdate update from calculation graph msg=config:<key:"CalicoVersion" value:"v2.6.3" > config:<key:"ClusterGUID" value:"9bab904a74fc4f039fc413b963c014a4" > config:<key:"ClusterType" value:"KDD,k8s,bgp" > config:<key:"DatastoreType" value:"kubernetes" > config:<key:"DefaultEndpointToHostAction" value:"ACCEPT" > config:<key:"FelixHostname" value:"internal1-controller1" > config:<key:"HealthEnabled" value:"true" > config:<key:"IpInIpEnabled" value:"true" > config:<key:"IpInIpMtu" value:"1440" > config:<key:"IpInIpTunnelAddr" value:"172.20.1.1" > config:<key:"Ipv6Support" value:"false" > config:<key:"LogFilePath" value:"None" > config:<key:"LogSeverityFile" value:"None" > config:<key:"LogSeverityScreen" value:"info" > config:<key:"LogSeveritySys" value:"None" > config:<key:"MetadataAddr" value:"None" > config:<key:"ReportingIntervalSecs" value:"0" > 
2018-01-23 11:39:02.231 [INFO][717] health.go 144: Starting health endpoints port=9099
2018-01-23 11:39:02.231 [INFO][717] felix.go 570: No driver process to monitor
2018-01-23 11:39:02.233 [INFO][717] syncer.go 656: Syncing NetworkPolicy
2018-01-23 11:39:02.238 [PANIC][717] conversion.go 448: Invalid port %+v: %spostgresql invalid port format (postgresql)
panic: (*logrus.Entry) (0x172b720,0xc4202724b0)

goroutine 71 [running]:
github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus.Entry.log(0xc420014f50, 0xc4200130e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420013000, ...)
        /go/src/github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus/entry.go:124 +0x340
github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc4202723c0, 0xc42088cfe8, 0x3, 0x3)
        /go/src/github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus/entry.go:169 +0x11b
github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus.(*Logger).Panic(0xc420014f50, 0xc42088cfe8, 0x3, 0x3)
        /go/src/github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus/logger.go:235 +0x6e
github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus.Panic(0xc42088cfe8, 0x3, 0x3)
        /go/src/github.com/projectcalico/felix/vendor/github.com/sirupsen/logrus/exported.go:107 +0x4b
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.Converter.k8sPortToCalico(0xc42015a160, 0xc420108f60, 0x3, 0x3, 0xc42015a180)
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/conversion.go:448 +0x150
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.Converter.k8sPortToCalicoFields(0xc42015a150, 0xc42088d0c0, 0x0, 0x0, 0x1)
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/conversion.go:391 +0x5b
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.Converter.k8sRuleToCalico(0xc4208ca780, 0x1, 0x10, 0xc420336d00, 0x1, 0x10, 0xc420392e77, 0x3, 0xc420012f01, 0x0, ...)
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/conversion.go:356 +0x7a9
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.Converter.NetworkPolicyToPolicy(0xc42088e630, 0xc42013c180, 0xc42088de68, 0xc4201c6088)
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/conversion.go:203 +0x262
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*kubeSyncer).performSnapshot(0xc420824fa0, 0xc4201d36c0, 0xc420841488, 0x1)
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/syncer.go:671 +0x3c35
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*kubeSyncer).readFromKubernetesAPI(0xc420824fa0)
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/syncer.go:329 +0x404
created by github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*kubeSyncer).Start
        /go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/syncer.go:221 +0x3f

```

## Context

Kubernetes spec says regarding `port` field in network policy rules:

Field |  Description
-- | --
port | The port on the given protocol. This can either be a numerical or  **named port on a pod**. If this field is not provided, this matches all  port names and numbers.

## Your Environment
Calico 2.6.3

**Comment by fasaxc** [comment]
Support for named ports was added in Calico v3.0.0.

**Comment by fasaxc** [comment]
We really shouldn't crash on a validation failure in v2.x, though.

**Comment by redbaron** [comment]
@fasaxc I can see `You can now name host and workload endpoint ports and reference them by name in your policy rules.` in release notes, but it doesn't match what I see in libcalico-go. Could it be that named ports are supported in  Calico policies, but crash happens when calico policy is created from Kubernetes policy.

**Comment by fasaxc** [comment]
@redbaron That feature was added in v3.0.0, but you said above that you were using v2.6.3, which doesn't have the feature.  It is a bug that we crash in v2.6.3 but if you want the feature, it is available in v3.0.x.

**Comment by redbaron** [comment]
I understand that it was added in 3.0.x,and I didn't try it yet, but just looking at latest https://github.com/projectcalico/libcalico-go/blob/b2eca7082417b2fd940ab3eaac6af793d7cb06ff/lib/backend/k8s/conversion/conversion.go#L549-L553 I can't see how it might possible work

Release notes on 3.0.x mentioned named ports in native Calico policy section, so I asked, could it be that once policy is generated , named ports can work indeed, but it looks to me that policy CAN NOT be generated from Kubernetes NetworkPolicy even for 3.0.x.

**Comment by fasaxc** [comment]
The conversion function was updated.  See: https://github.com/projectcalico/libcalico-go/blob/b2eca7082417b2fd940ab3eaac6af793d7cb06ff/lib/numorstring/port.go#L64

**Comment by caseydavenport** [comment]
I've got https://github.com/projectcalico/libcalico-go/pull/771/files to fix this in libcalico. Once merged we'll need to update Felix to pull in that version.

**Comment by caseydavenport** [comment]
Fix is in https://github.com/projectcalico/libcalico-go/pull/771

v2.6.7 should be out today :)
