### ISSUE TITLE
Failed to update IP sets after multiple retries

### ISSUE THREAD

**Issue by timyinshi** [projectcalico/felix#2083]
## Expected Behavior
hello，everyone,when i start calico-node,i find a  error,who know how to solve the error?
```
2019-07-19 08:46:27.011 [WARNING][886] ipsets.go 634: Failed to complete ipset restore, IP sets may be out-of-sync. closeErr=<nil> commitErr=<nil> family="inet" flushErr=<nil> input="create cali40all-ipam-pools hash:net family inet maxelem 1048576\ncreate cali4t32 hash:net family inet maxelem 1048576\nadd cali4t32 172.31.0.0/16\nswap cali40all-ipam-pools cali4t32\ndestroy cali4t32\ncreate cali40masq-ipam-pools hash:net family inet maxelem 1048576\ncreate cali4t33 hash:net family inet maxelem 1048576\nadd cali4t33 172.31.0.0/16\nswap cali40masq-ipam-pools cali4t33\ndestroy cali4t33\ncreate cali40this-host hash:ip family inet maxelem 1048576\ncreate cali4t34 hash:ip family inet maxelem 1048576\nadd cali4t34 10.200.72.6\nadd cali4t34 172.17.0.1\nadd cali4t34 172.31.49.0\nadd cali4t34 127.0.0.1\nswap cali40this-host cali4t34\ndestroy cali4t34\ncreate cali40all-hosts-net hash:net family inet maxelem 1048576\ncreate cali4t35 hash:net family inet maxelem 1048576\nadd cali4t35 10.200.72.1/32\nadd cali4t35 10.200.72.17/32\nadd cali4t35 10.200.72.6/32\nswap cali40all-hosts-net cali4t35\ndestroy cali4t35\nCOMMIT\n" processErr=exit status 1 stderr="ipset v6.29: Error in line 1: Kernel error received: set type not supported\n" stdout="" writeErr=<nil>
2019-07-19 08:46:27.015 [WARNING][886] ipsets.go 278: Failed to update IP sets. Marking dataplane for resync. error=exit status 1 family="inet"
2019-07-19 08:46:27.272 [INFO][886] int_dataplane.go 896: Retrying after an ipsets update failure... family="inet"
2019-07-19 08:46:27.273 [INFO][886] int_dataplane.go 896: Resyncing ipsets with dataplane. family="inet"
2019-07-19 08:46:27.287 [INFO][886] ipsets.go 561: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=13.690875ms
2019-07-19 08:46:27.299 [INFO][886] ipsets.go 611: Doing full IP set rewrite family="inet" numMembersInPendingReplace=1 setID="all-ipam-pools"
2019-07-19 08:46:27.301 [INFO][886] ipsets.go 611: Doing full IP set rewrite family="inet" numMembersInPendingReplace=1 setID="masq-ipam-pools"
2019-07-19 08:46:27.303 [INFO][886] ipsets.go 611: Doing full IP set rewrite family="inet" numMembersInPendingReplace=4 setID="this-host"
2019-07-19 08:46:27.303 [INFO][886] ipsets.go 611: Doing full IP set rewrite family="inet" numMembersInPendingReplace=3 setID="all-hosts-net"
2019-07-19 08:46:27.310 [WARNING][886] ipsets.go 634: Failed to complete ipset restore, IP sets may be out-of-sync. closeErr=<nil> commitErr=<nil> family="inet" flushErr=<nil> input="create cali40all-ipam-pools hash:net family inet maxelem 1048576\ncreate cali4t36 hash:net family inet maxelem 1048576\nadd cali4t36 172.31.0.0/16\nswap cali40all-ipam-pools cali4t36\ndestroy cali4t36\ncreate cali40masq-ipam-pools hash:net family inet maxelem 1048576\ncreate cali4t37 hash:net family inet maxelem 1048576\nadd cali4t37 172.31.0.0/16\nswap cali40masq-ipam-pools cali4t37\ndestroy cali4t37\ncreate cali40this-host hash:ip family inet maxelem 1048576\ncreate cali4t38 hash:ip family inet maxelem 1048576\nadd cali4t38 127.0.0.1\nadd cali4t38 10.200.72.6\nadd cali4t38 172.17.0.1\nadd cali4t38 172.31.49.0\nswap cali40this-host cali4t38\ndestroy cali4t38\ncreate cali40all-hosts-net hash:net family inet maxelem 1048576\ncreate cali4t39 hash:net family inet maxelem 1048576\nadd cali4t39 10.200.72.1/32\nadd cali4t39 10.200.72.17/32\nadd cali4t39 10.200.72.6/32\nswap cali40all-hosts-net cali4t39\ndestroy cali4t39\nCOMMIT\n" processErr=exit status 1 stderr="ipset v6.29: Error in line 1: Kernel error received: set type not supported\n" stdout="" writeErr=<nil>
2019-07-19 08:46:27.316 [WARNING][886] ipsets.go 278: Failed to update IP sets. Marking dataplane for resync. error=exit status 1 family="inet"
2019-07-19 08:46:27.801 [INFO][886] health.go 111: Overall health summary=&health.HealthReport{Live:true, Ready:false}
2019-07-19 08:46:27.841 [INFO][886] ipsets.go 289: Current state of IP sets family="inet" output=""
2019-07-19 08:46:27.843 [PANIC][886] int_dataplane.go 896: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) (0x1216f3ae0,0xc0007ba550)

goroutine 195 [running]:
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000ee050, 0xc0005e3230, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:128 +0x680
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc0000ee5f0, 0xc0005c9be0, 0x1, 0x1)
	/opt/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:173 +0xfc
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0xc0002c6a20)
	/opt/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ipsets/ipsets.go:290 +0x34c
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0xc00051c6c0, 0xc0002c6a20)
	/opt/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:896 +0x3c
created by github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
	/opt/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:895 +0x2e8
```
## Current Behavior
the calico-node has a error.

## Steps to Reproduce (for bugs)
start calico-node

## Your Environment
* Felix version (if using Felix binary directly `calico-felix --version`):3.4.0
* And/Or, `calico/node` container version (if running Felix in a container):3.4.0
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):kubernetes
* Etcd version (if using etcd datastore driver):v3.2.26
* Operating System and version:NeoKylin Linux Server 7.0 (loongson)

**Comment by fasaxc** [comment]
> Kernel error received: set type not supported

You're probably missing the IP set kernel modules.  We try to load those automatically if they're mounted into the pod.  Otherwise, you'll need to modprobe them before starting calico.

**Comment by timyinshi** [comment]
ok,thanks,i use the command ,find the error is :
 calicoctl node checksystem
Checking kernel version...
		3.10.0-693.5.2.ns7.032.mips64el					OK
Checking kernel modules...
WARNING: Unable to detect the xt_set module as Loaded/Builtin module or lsmod
		xt_set              					FAIL
		ip6_tables          					OK

**Comment by rafaelvanoni** [comment]
@timyinshi Please check if you can reproduce the error once all the necessary modules are loaded. Let us know if you still need help with this.

**Comment by timyinshi** [comment]
ok,thanks
