### ISSUE TITLE
Calico Pod unhealthy - Felix has problems with IPSet

### ISSUE THREAD

**Issue by finewhin** [projectcalico/felix#2607]
Looks like Calico isn't getting healthy because of Felix.

## Context
The Pods can't communicate to each other nor the Internet

## Your Environment
I've got Kubernetes running on Jetson Nanos, the Image is: calico/cni:v3.14.2

If looking at the logs from the Container I found the following error:
```
2020-11-25 13:24:29.710 [INFO][478] felix/ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=9.656833ms
2020-11-25 13:24:29.710 [WARNING][478] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2020-11-25 13:24:29.968 [INFO][478] felix/ipsets.go 301: Retrying after an ipsets update failure... family="inet"
2020-11-25 13:24:29.971 [INFO][478] felix/ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
2020-11-25 13:24:29.993 [ERROR][478] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2020-11-25 13:24:29.993 [INFO][478] felix/ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=21.779138ms
2020-11-25 13:24:29.993 [WARNING][478] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2020-11-25 13:24:30.233 [INFO][478] felix/ipip_mgr.go 106: Failed to get IPIP tunnel device, assuming it isn't present error=Link not found
2020-11-25 13:24:30.259 [WARNING][478] felix/ipip_mgr.go 112: Failed to add IPIP tunnel device error=exit status 1
2020-11-25 13:24:30.259 [WARNING][478] felix/ipip_mgr.go 89: Failed configure IPIP tunnel device, retrying... error=exit status 1
2020-11-25 13:24:30.537 [ERROR][478] felix/ipsets.go 916: Failed to read IP sets error=exit status 1 family="inet"
2020-11-25 13:24:30.538 [PANIC][478] felix/ipsets.go 342: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) (0x17090a0,0x40007860a0)

goroutine 180 [running]:
github.com/sirupsen/logrus.Entry.log(0x40000cc180, 0x400044f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x5d4
github.com/sirupsen/logrus.(*Entry).Panic(0x40000d5180, 0x400081bbb8, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xb4
github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0x400022f9e0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200526093357-ca5e8bf263c4/ipsets/ipsets.go:342 +0x2bc
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0x4000102100, 0x40007aea14, 0x400022f9e0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200526093357-ca5e8bf263c4/dataplane/linux/int_dataplane.go:1358 +0x28
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200526093357-ca5e8bf263c4/dataplane/linux/int_dataplane.go:1357 +0x310
```

Please help me find the issue.

**Comment by song-jiang** [comment]
Could you provide your Linux kernel version? Looks like `ipsets` utility used by Felix is not compatible with your kernel?

**Comment by caseydavenport** [comment]
@finewhin any update on this?

**Comment by finewhin** [comment]
I‘m sorry I forgot this issue. I can‘t provide any further information since I switched to Flannel. So I‘m closing now.

**Comment by ktsakalozos** [comment]
@finewhin @song-jiang this error is reported on MicroK8s at https://github.com/ubuntu/microk8s/issues/2110. 

Here is some more info on the kernel and distribution:
```
ubuntu@xaviernx:~$ uname -a
Linux xaviernx 4.9.140-tegra #1 SMP PREEMPT Tue Oct 27 21:02:46 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@xaviernx:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

I am able to reproduce the error on 3.18, 3.17, 3.13 release series.
