### ISSUE TITLE
Suggestion needed with calico-node FELIX_BPFENABLED and PodSecurityPolicy

### ISSUE THREAD

**Issue by oleksii-danchuk** [projectcalico/felix#2650]
## Expected Behavior

Calico node up and running.

## Current Behavior

Hi All,
I'm getting an Error to run calico-node with bpf enabled.
Not sure it's a bug, as I suspect PodSecurityPolicy, but I tried with least restrictive policy as here: 
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/privileged-psp.yaml
plus
```
allowedUnsafeSysctls:
  - '*'
```
and 
```
allowedProcMountTypes:
  - 'Unmasked'
  - 'Default'
```
Docker has 
`MountFlags=shared`

Calico ds contains:
```
capabilities:
      add:
          - SYS_ADMIN
          - NET_ADMIN
          - NET_BIND_SERVICE
```
Log:
```
2020-12-29 20:57:34.060 [INFO][3681] felix/int_dataplane.go 493: BPF enabled, starting BPF endpoint manager and map manager.
2020-12-29 20:57:34.060 [INFO][3681] felix/maps.go 283: Loaded map file descriptor. fd=0x13 name="/sys/fs/bpf/tc/globals/cali_v4_state"
2020-12-29 20:57:34.061 [INFO][3681] felix/maps.go 269: Looking for map by name (to repin it) name="cali_v4_nat_fe"
2020-12-29 20:57:34.064 [ERROR][3681] felix/maps.go 312: Failed to run bpftool out="Error: map create failed: Operation not permitted\n"
2020-12-29 20:57:34.064 [PANIC][3681] felix/int_dataplane.go 535: Failed to create NAT frontend BPF map. error=exit status 255
panic: (*logrus.Entry) (0x22c0400,0xc0002414a0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0001121e0, 0xc0006513b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x68a
github.com/sirupsen/logrus.(*Entry).Panic(0xc000241450, 0xc0009e9518, 0x1, 0x1)
        /go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0x102
github.com/projectcalico/felix/dataplane/linux.NewIntDataplaneDriver(0xc000050254, 0x8, 0x0, 0x0, 0x0, 0x5a0, 0x5a0, 0x100000, 0x1e32df9, 0x4, ...)
        /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201105032738-d639c9d1f1f4/dataplane/linux/int_dataplane.go:535 +0x362a
github.com/projectcalico/felix/dataplane.StartDataplaneDriver(0xc00033ec00, 0xc000123770, 0xc0008ed480, 0xc0006a3340, 0xc0009eb688, 0x0, 0x0)
        /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201105032738-d639c9d1f1f4/dataplane/driver.go:289 +0x12d4
github.com/projectcalico/felix/daemon.Run(0x2334068, 0x15, 0x27e0220, 0x7, 0x287e340, 0x28, 0x283d610, 0x18)
        /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201105032738-d639c9d1f1f4/daemon/daemon.go:377 +0x1ef3
main.main()
        /go/src/github.com/projectcalico/node/cmd/calico-node/main.go:109 +0x616
```

One of the node ignore the setting, cannot understand why...Should I revoke etcd datastore after I delete calico-node ds?
```
2020-12-29 21:40:39.160 [INFO][52] felix/config_params.go 335: Merging in config from datastore (per-host): map[DefaultEndpointToHostAction:Return IpInIpTunnelAddr:10.244.122.128]
2020-12-29 21:40:39.160 [INFO][52] felix/config_params.go 424: Parsing value for BPFEnabled: false (from internal override)
2020-12-29 21:40:39.160 [INFO][52] felix/config_params.go 460: Parsed value for BPFEnabled: false (from internal override)
2020-12-29 21:40:39.160 [INFO][52] felix/config_params.go 424: Parsing value for BPFEnabled: true (from environment variable)
2020-12-29 21:40:39.160 [INFO][52] felix/config_params.go 460: Parsed value for BPFEnabled: true (from environment variable)
2020-12-29 21:40:39.160 [INFO][52] felix/config_params.go 463: Skipping config value for BPFEnabled from environment variable; already have a value from internal override
```
Official docs says just a few words about Privileges
https://docs.projectcalico.org/getting-started/kubernetes/requirements

You share a lot of yaml examples to configure calico, but is there some example for PodSecurityPolicy?

## Possible Solution

N/A, maybe disable PodSecurityPolicy addmission controller, which is not the best option for me...
## Steps to Reproduce (for bugs)

Not relevant.

## Context

I am trying to replace kube-proxy with calico bpf.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`): not dirrect
* And/Or, `calico/node` container version (if running Felix in a container):  calico-node v3.16.5
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes 
* Orchestrator version (if used): 1.19.6
* Etcd version (if using etcd datastore driver): 3.4.14
* Operating System and version: 
Fedora 33 (Cloud Edition)      5.9.16-200.fc33.x86_64
CentOS Linux 8                     4.18.0-240.1.1.el8_3.x86_64
* Link to your project (optional): just a lab

**Comment by tomastigera** [comment]
> CentOS Linux 8 4.18.0-240.1.1.el8_3.x86_64

You need a newer kernel. We support 5.3+

**Comment by tomastigera** [comment]
It might be that bpffs is not mounted / available. Or BPF support is not enabled. Or some features are missing from the kernel. We do support Red Hat v8.2 with Linux kernel v4.18.0-193 or above, not sure if that would apply to CentOS too.

could you set `FELIX_LOGSEVERITYSCREEN` to `debug`.

**Comment by oleksii-danchuk** [comment]
I checked using this docs
https://docs.projectcalico.org/maintenance/enabling-bpf#verify-that-your-cluster-is-ready-for-ebpf-mode
```
mount | grep "/sys/fs/bpf"
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
```
Looks like it mounted ok.

I tried to disabled selinux - the same result.

Here the logs with debug enabled:
```
2020-12-30 19:12:26.999 [DEBUG][406] felix/bpf.go 154: running: bpftool prog detach pinned /sys/fs/bpf/calico/sockmap/calico_sk_msg_v1 msg_verdict pinned /sys/fs/bpf/calico/sockmap/calico_sock_map_v1
2020-12-30 19:12:27.003 [DEBUG][406] felix/sockmap_state.go 194: Failed to detach sk_msg program from sockmap. error=failed to detach sk_msg prog from sockmap: exit status 255
Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sk_msg_v1): No such file or directory

2020-12-30 19:12:27.003 [DEBUG][406] felix/bpf.go 154: running: bpftool cgroup detach /run/calico/cgroup sock_ops pinned /sys/fs/bpf/calico/sockmap/calico_sockops_v1
2020-12-30 19:12:27.005 [DEBUG][406] felix/sockmap_state.go 198: Failed to detach sockops program from cgroup. error=failed to detach sockops prog from cgroup: exit status 255
Error: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sockops_v1): No such file or directory

2020-12-30 19:12:27.005 [DEBUG][406] felix/sockmap_state.go 202: Failed to remove sockops program. error=remove /sys/fs/bpf/calico/sockmap/calico_sockops_v1: no such file or directory
2020-12-30 19:12:27.005 [DEBUG][406] felix/sockmap_state.go 206: Failed to remove sk_msg program. error=remove /sys/fs/bpf/calico/sockmap/calico_sk_msg_v1: no such file or directory
2020-12-30 19:12:27.005 [DEBUG][406] felix/sockmap_state.go 210: Failed to remove sockmap endpoints map. error=remove /sys/fs/bpf/calico/sockmap/calico_sk_endpoints_v1: no such file or directory
2020-12-30 19:12:27.005 [DEBUG][406] felix/bpf.go 154: running: bpftool map --json getnext pinned /sys/fs/bpf/calico/sockmap/calico_sock_map_v1
2020-12-30 19:12:27.007 [DEBUG][406] felix/sockmap_state.go 214: Failed to remove sockmap program. error=failed to clear sock map: bpf obj get (/sys/fs/bpf/calico/sockmap/calico_sock_map_v1): No such file or directory
2020-12-30 19:12:27.007 [INFO][406] felix/int_dataplane.go 493: BPF enabled, starting BPF endpoint manager and map manager.
2020-12-30 19:12:27.008 [DEBUG][406] felix/maps.go 278: Map file already exists, trying to open it
2020-12-30 19:12:27.008 [DEBUG][406] felix/bpf_syscall.go 197: GetMapFDByPin(/sys/fs/bpf/tc/globals/cali_v4_state)
2020-12-30 19:12:27.008 [INFO][406] felix/maps.go 283: Loaded map file descriptor. fd=0x16 name="/sys/fs/bpf/tc/globals/cali_v4_state"
2020-12-30 19:12:27.008 [DEBUG][406] felix/maps.go 267: Map file didn't exist
2020-12-30 19:12:27.008 [INFO][406] felix/maps.go 269: Looking for map by name (to repin it) name="cali_v4_nat_fe"
2020-12-30 19:12:27.010 [DEBUG][406] felix/maps.go 335: Got map metadata. maps="[{\"id\":1,\"type\":\"percpu_array\",\"name\":\"cali_v4_state\",\"flags\":0,\"bytes_key\":4,\"bytes_value\":64,\"max_entries\":1,\"bytes_memlock\":4096}]\n"
2020-12-30 19:12:27.010 [DEBUG][406] felix/maps.go 301: Map didn't exist, creating it
2020-12-30 19:12:27.012 [ERROR][406] felix/maps.go 312: Failed to run bpftool out="Error: map create failed: Operation not permitted\n"
2020-12-30 19:12:27.012 [PANIC][406] felix/int_dataplane.go 535: Failed to create NAT frontend BPF map. error=exit status 255
```
Probably i will skip the idea to switch to bpf for now.

Thank you for your time.
